### PR TITLE
Update go.mod module name to match with repo

### PR DESCRIPTION
**Pull request by Luke-Roy-IBM**

### CODE REVIEW

**Comment by Luke-Roy-IBM** [comment]
Hi @aarzilli and @derekparker,
What do you think can this be merged?

**Comment by aarzilli** [comment]
motivation?

**Comment by wabscale** [comment]
I'm not sure what changed in go, but trying to install this now gives this error:

```
#0 178.2 go get: github.com/go-delve/liner@v1.2.2: parsing go.mod:
#0 178.2 	module declares its path as: github.com/peterh/liner
#0 178.2 	        but was required as: github.com/go-delve/liner
```

**Comment by aarzilli** [comment]
Go get is not the recommended way to install Delve (or anything else): https://github.com/go-delve/delve/tree/master/Documentation/installation

**Comment by wabscale** [comment]
It may not be recommend but lots of projects have scripts that were written years ago that do go get. All of those projects that go get this tool all just broke.

I'm really not understanding what the issue is with merging this PR. It doesn't break anything, fixes a minor error in the go.mod, and continues backwards compatibility with everything that depends on it.

**Comment by Luke-Roy-IBM** [comment]
@aarzilli like @wabscale  said the motivation was to keep support for older projects that are still using `go get`

**Review by derekparker — APPROVED** [review]
LGTM - I'm fine with merging this.

**Comment by Luke-Roy-IBM** [comment]
@derekparker Thanks :)

**Comment by aarzilli** [comment]
Just as a sidenote, I think go get to install won't work anymore with 1.18.

**Pull request merged**
